/* Generated by tools/gen_sjis_level1_table.php. Do not edit manually. */

#ifndef SJIS_LEVEL1_TABLE_H
#define SJIS_LEVEL1_TABLE_H

#include <stddef.h>
#include <stdint.h>

typedef struct {
    uint16_t unicode;
    uint16_t sjis;
} utf8_sjis_map_t;

extern const utf8_sjis_map_t utf8_to_sjis_level1_table[];
extern const size_t utf8_to_sjis_level1_table_count;

#endif
