<?php

declare(strict_types=1);

mb_internal_encoding('UTF-8');
mb_substitute_character('none');

const SJIS_LEVEL1_START = 0x889F;
const SJIS_LEVEL1_END = 0x9872;
const OUTPUT_DIR = __DIR__ . '/../pico_tnc';

function sjis_to_uint16(string $sjis): int
{
    return (ord($sjis[0]) << 8) | ord($sjis[1]);
}

function is_sjis_level1(int $sjisCode): bool
{
    return $sjisCode >= SJIS_LEVEL1_START && $sjisCode <= SJIS_LEVEL1_END;
}

function utf8_from_codepoint(int $codepoint): string
{
    return mb_convert_encoding(pack('N', $codepoint), 'UTF-8', 'UTF-32BE');
}

$entries = [];
for ($cp = 0x0000; $cp <= 0xFFFF; $cp++) {
    $utf8 = utf8_from_codepoint($cp);
    $sjis = mb_convert_encoding($utf8, 'SJIS', 'UTF-8');
    if (strlen($sjis) !== 2) {
        continue;
    }

    $sjisCode = sjis_to_uint16($sjis);
    if (!is_sjis_level1($sjisCode)) {
        continue;
    }

    $roundTrip = mb_convert_encoding($sjis, 'UTF-8', 'SJIS');
    if ($roundTrip !== $utf8) {
        continue;
    }

    $entries[] = [
        'unicode' => $cp,
        'sjis' => $sjisCode,
    ];
}

$header = [];
$header[] = '/* Generated by tools/gen_sjis_level1_table.php. Do not edit manually. */';
$header[] = '';
$header[] = '#ifndef SJIS_LEVEL1_TABLE_H';
$header[] = '#define SJIS_LEVEL1_TABLE_H';
$header[] = '';
$header[] = '#include <stddef.h>';
$header[] = '#include <stdint.h>';
$header[] = '';
$header[] = 'typedef struct {';
$header[] = '    uint16_t unicode;';
$header[] = '    uint16_t sjis;';
$header[] = '} utf8_sjis_map_t;';
$header[] = '';
$header[] = 'extern const utf8_sjis_map_t utf8_to_sjis_level1_table[];';
$header[] = 'extern const size_t utf8_to_sjis_level1_table_count;';
$header[] = '';
$header[] = '#endif';
$header[] = '';

$output = [];
$output[] = '/* Generated by tools/gen_sjis_level1_table.php. Do not edit manually. */';
$output[] = '#include "sjis_level1_table.h"';
$output[] = '';
$output[] = 'const utf8_sjis_map_t utf8_to_sjis_level1_table[] = {';

$line = [];
$lineChars = [];
foreach ($entries as $index => $entry) {
    $line[] = sprintf('{0x%04X, 0x%04X}', $entry['unicode'], $entry['sjis']);
    $lineChars[] = utf8_from_codepoint($entry['unicode']);
    if (count($line) === 8) {
        $output[] = '    // ' . implode(' ', $lineChars);
        $output[] = '    ' . implode(', ', $line) . ',';
        $line = [];
        $lineChars = [];
    }
}
if (count($line) > 0) {
    $output[] = '    // ' . implode(' ', $lineChars);
    $output[] = '    ' . implode(', ', $line) . ',';
}

$output[] = '};';
$output[] = '';
$output[] = 'const size_t utf8_to_sjis_level1_table_count =';
$output[] = '    sizeof(utf8_to_sjis_level1_table) / sizeof(utf8_to_sjis_level1_table[0]);';
$output[] = '';

file_put_contents(OUTPUT_DIR . '/sjis_level1_table.h', implode(PHP_EOL, $header));
file_put_contents(OUTPUT_DIR . '/sjis_level1_table.c', implode(PHP_EOL, $output));

echo 'Generated pico_tnc/sjis_level1_table.h and pico_tnc/sjis_level1_table.c with '
    . count($entries) . " entries." . PHP_EOL;
